import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { montserrat, montserratAlternates } from "@/lib/fonts";
import { createClient } from "@/lib/supabase/server";
import { AuthProvider, type AuthUser } from "@/components/auth/auth-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const supabase = await createClient();
  const { data } = await supabase.auth.getClaims();
  const initialUser: AuthUser = data?.claims
    ? { id: data.claims.sub, email: (data.claims.email as string | undefined) ?? null }
    : null;

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${montserratAlternates.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider>
          <AuthProvider initialUser={initialUser}>{children}</AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
