import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { montserrat, montserratAlternates } from "@/lib/fonts";
import { createClient } from "@/lib/supabase/server";
import { Toaster } from "sonner";
import { AuthProvider, type AuthUser } from "@/components/auth/auth-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sun* Kudos",
  description: "Generated by Sun* Kudos",
  icons: {
    icon: "/login/sun-logo.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const supabase = await createClient();
  // getClaims() throws (not returns an error) when the refresh token is stale/revoked — treat as no session.
  const claims = await supabase.auth.getClaims().then(
    ({ data }) => data?.claims,
    () => undefined
  );
  const initialUser: AuthUser = claims
    ? { id: claims.sub, email: (claims.email as string | undefined) ?? null }
    : null;

  return (
    <html
      lang={locale}
      className={`${montserrat.variable} ${montserratAlternates.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* Rendered BEFORE {children} on purpose: React fires mount effects in
           tree order (a subtree's effects all run before the next sibling's),
           so a `<Toaster/>` placed after {children} would still be
           subscribing to sonner's store *after* something deep inside
           {children} (e.g. LoginToastListener, whose effect fires on the very
           first paint) already called `toast.success()` — that call landed
           with nobody listening yet and silently vanished. */}
        <Toaster
          position="bottom-left"
          theme="dark"
          richColors
          duration={3000}
          toastOptions={{ classNames: { toast: "font-montserrat" } }}
        />
        <NextIntlClientProvider>
          <AuthProvider initialUser={initialUser}>{children}</AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
